Reinstate missing (ceased) members
everypolitician-scrapers/mexico-diputados-2015 pull request #2
Opened 2016-09-15 15:50 UTC by octopusinvitro

Some members have ceased their functions in this legislature, so they were removed from the official site and we were losing them. However, their old dedicated pages are still there. 

This commit puts back the information that we previously had about them by hardcoding the urls to their dedicated pages.

2016-09-23 07:27 UTC, tmtmtmtm commented on scraper.rb
> +    name:noko.css('td strong').find { |n| n.text.include? 'Dip. ' }.text.sub('Dip. ','').sub(' (LICENCIA)', '').sub(' (no rindieron protesta)', '').sub(' (pendiente protesta)', '').tidy,
This line was already straining under the weight of multiple subs — adding another couple definitely pushes it over the edge.

2016-09-23 07:28 UTC, tmtmtmtm commented on scraper.rb
> +    sort_name: '',
Why no `sort_name`?

2016-09-23 07:29 UTC, tmtmtmtm commented on scraper.rb
> +]
perhaps better to set this up as a list of ids, and then add those into the URL in the `each`?

2016-09-23 07:38 UTC, tmtmtmtm requested changes
This approach makes me a little uncomfortable. As I understand it, the old approach was to gather as much information as possible off the list page, and then go to the individual member pages for information that wasn't there.

But now we need to include people who aren't _on_ the index page, so we scrape their personal page twice?

Perhaps it would be cleaner to always get all of the information off the personal page now that the initial conditions no longer hold? 

Either way, I think this is also time to rewrite this to be a class-based scraper: the current approach is straining a little too much now.

2016-11-18 16:35 UTC, octopusinvitro commented
Closing this as it was the wrong approach

2016-11-18 16:35 UTC, closed without merging